### ISSUE TITLE
Add RollForward to support .NET 6

### ISSUE THREAD

**Issue by isaiahpettingill** [angelobreuer/localtunnel.net#15]
This tool does not support .net 6.

You can make it support .NET 6 one of two ways,

1. Set <RollForward > in csproj
See https://stackoverflow.com/questions/71272243/building-a-net5-0-targeted-app-which-can-run-on-net6-0-runtime

2. Upgrade to .NET 6

**Comment by angelobreuer** [comment]
Thank you! I will push the NuGet packages in a few minutes. Please reopen the issue, if there are follow-up issues related to this
