### ISSUE TITLE
Query parameters are lost

### ISSUE THREAD

**Issue by a-stankevich** [angelobreuer/localtunnel.net#17]
Using localtunnel.net 1.0.4 with latest localtunnel-server docker image.

Query parameters from URL are not passed to the HTTP server when forwarding thorugh localtunnel:

![image](https://user-images.githubusercontent.com/6768522/184620467-cf629e9e-93cb-46e0-8166-ee48bb82671f.png)

Parameters are visible in localtunnel-server logs:

![image](https://user-images.githubusercontent.com/6768522/184620549-f1bb7dd9-a7c8-47c8-9892-1ecc6ef736c1.png)

Works when sending request directly:

![image](https://user-images.githubusercontent.com/6768522/184620501-35698b16-3830-491d-a15a-fc5734918c85.png)

**Comment by a-stankevich** [comment]
https://github.com/angelobreuer/localtunnel.net/blob/feat/server/src/Localtunnel.Server/TunnelInformation.cs#L72 this needs to include querystring

**Comment by angelobreuer** [comment]
Thank you, I pushed a new docker image with the changes to include the query string

**Comment by angelobreuer** [comment]
Stale

**Comment by a-stankevich** [comment]
This is fixed now, thank you!
