### ISSUE TITLE
localtunnel library does not connect to hosted localtunnel instance

### ISSUE THREAD

**Issue by dustyroberts** [angelobreuer/localtunnel.net#24]
Specifying my own hostname and subdomain on the client does not work for some reason

           var pipeline = new HttpRequestProcessingPipelineBuilder()
                .Append(new HttpHostHeaderRewritingRequestProcessor("lt.moonlighting.dev"))
                .Build();

            var endpointFactory = new HttpsTunnelEndpointFactory("lt.moonlighting.dev", 443);

i then specify the subdomain:

            var tunnel = await client
                .OpenAsync(tunnelConnectionHandler, subdomain: $"random-api")
                .ConfigureAwait(false);

and for some reason it does not connect. If I use the CLI tool it works perfectly

Correction, it connects, but to loca.lt which is not the specified domain though...

**Comment by angelobreuer** [comment]
You are trying to specify your localtunnel server as the remote endpoint. You need to set the base address to the server instead. See here:

```csharp
using Localtunnel;
using Localtunnel.Endpoints.Http;
using Localtunnel.Handlers.Kestrel;
using Localtunnel.Processors;
using Microsoft.Extensions.Logging;

// Create logger factory to enable logging
var loggerFactory = LoggerFactory.Create(x => x.AddConsole().SetMinimumLevel(LogLevel.Trace));

var baseAddress = new Uri("https://lt.moonlighting.dev/"); // HERE

// You can also pass null as the loggerFactory to disable logging
using var client = new LocaltunnelClient(baseAddress, loggerFactory); // and HERE

// Build the processor pipeline
var pipeline = new HttpRequestProcessingPipelineBuilder()
    // Rewrite the host header to match the target server's host
    .Append(new HttpHostHeaderRewritingRequestProcessor("test.angelobreuer.de"))
    .Build();

// Contact the destination server using HTTPS
var endpointFactory = new HttpsTunnelEndpointFactory("test.angelobreuer.de", 443);

// Build tunnel connection handler
var tunnelConnectionHandler = new KestrelTunnelConnectionHandler(pipeline, endpointFactory);

// Open the tunnel
var tunnel = await client
    .OpenAsync(tunnelConnectionHandler)
    .ConfigureAwait(false);

// Start accepting requests
await tunnel
    .StartAsync()
    .ConfigureAwait(false);

// Keep tunnel running
await Task.Delay(-1).ConfigureAwait(false);
```

**Comment by dustyroberts** [comment]
apologies for sounding like a tool ... but what would "test.angelobreuer.de" in this instance be?

**Comment by angelobreuer** [comment]
This would be the site the tunnel will forward traffic to. So I you would open the tunnel page in the browser, the tunnel would proxy traffic to the page (here: `test.angelobreuer.de`).

The library allows you to do anything with the traffic you want, the `HttpTunnelEndpointFactory` and `HttpsTunnelEndpointFactory` are predefined implementations that forward the traffic to another web server.

**Comment by dustyroberts** [comment]
Thanx for the quick reply.

I am using this in container while debugging :) 

Does it then make sense to have:

`new HttpHostHeaderRewritingRequestProcessor("localhost")`

and

`var endpointFactory = new HttpsTunnelEndpointFactory("localhost", <DOCKER PORT>);`

**Comment by angelobreuer** [comment]
Yes, that would be correct. The `HttpHostHeaderRewritingRequestProcessor` is used for domains that select the destination server by checking the `Host` header. One would use the HttpsTunnelEndpointFactory if the destination is a secured server (TLS) or HttpTunnelEndpointFactory for plain HTTP traffic.

**Comment by angelobreuer** [comment]
Stale
